name: GADS CI

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Swagger Generator
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger Documentation
        run: |
          swag init -g hub/hub.go -o docs

      - name: Build binaries
        run: |
          go get
          echo "Preparing Windows binary"
          GOOS=windows GOARCH=amd64 go build -ldflags="-X 'main.AppVersion=$RELEASE_TAG'" -o GADS.exe .
          zip -j gads-win.zip GADS.exe
          rm GADS.exe
          echo "Preparing macOS amd64 binary"
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'main.AppVersion=$RELEASE_TAG'" -o GADS .
          zip -j gads-mac-amd64.zip GADS
          rm GADS
          echo "Preparing macOS arm64 binary"
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'main.AppVersion=$RELEASE_TAG'" -o GADS .
          zip -j gads-mac-arm64.zip GADS
          rm GADS
          echo "Preparing Linux binary"
          GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.AppVersion=$RELEASE_TAG'" -o GADS .
          zip -j gads-linux.zip GADS
          rm GADS

      - uses: AButler/upload-release-assets@v2.0
        with:
          files: '*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
